version: '3'
services: 
    video-streaming:
        image: video-streaming
        build:
            context: ./video-streaming
            dockerfile: Dockerfile
        container_name: video-streaming
        ports: 
            - "4001:80"
        environment: 
            - PORT=80
            - VIDEO_STORAGE_HOST=video-storage
            - VIDEO_STORAGE_PORT=80
            - DB_HOST=mongodb://db:27017
            - DB_NAME=video-streaming
            - RABBIT=amqp://guest:guest@rabbit:5672
        restart: "no"
    # azure-storage:
    #     image: azure-storage
    #     build:
    #         context: ./azure-storage
    #         dockerfile: Dockerfile
    #     container_name: video-storage
    #     ports:
    #         - "4001:80"
    #     environment: 
    #         - PORT=80
    #         - STORAGE_ACCOUNT_NAME=xxx
    #         - STORAGE_ACCESS_KEY=xxx
    #     restart: "no"
    db:
        image: mongo:4.2.8
        container_name: db
        ports:
            - "4000:27017"
        restart: "always"
    history:
        image: history
        build:
            context: ./history
            dockerfile: Dockerfile-dev
        container_name: history
        volumes:
            - /tmp/history/npm-cache:/root/.npm:z
            - ./history/src:/usr/src/app/src:z
        ports: 
            - "4002:80"
        environment: 
            - PORT=80
            - NODE_ENV=development
            - DB_HOST=mongodb://db:27017
            - DB_NAME=video-streaming
            - RABBIT=amqp://guest:guest@rabbit:5672
        depends_on: 
            - db
            - rabbit
        restart: "no"
    rabbit:
        image: rabbitmq:3.8.1-management
        container_name: rabbit
        ports: 
            - "5672:5672"
            - "15672:15672"
        expose: 
            - "5672"
            - "15672"
        restart: "always"