version: '3'
services: 
    video-streaming:
        image: video-streaming
        build:
            context: ./video-streaming
            dockerfile: Dockerfile
        container_name: video-streaming
        ports: 
            - "4002:80"
        environment: 
            - PORT=80
            - VIDEO_STORAGE_HOST=video-storage
            - VIDEO_STORAGE_PORT=80
            - DB_HOST=mongodb://db:27017
            - DB_NAME=video-streaming
        restart: "no"
    azure-storage:
        image: azure-storage
        build:
            context: ./azure-storage
            dockerfile: Dockerfile
        container_name: video-storage
        ports:
            - "4001:80"
        environment: 
            - PORT=80
            - STORAGE_ACCOUNT_NAME=xxx
            - STORAGE_ACCESS_KEY=xxx
        restart: "no"
    db:
        image: mongo:4.2.8
        container_name: db
        ports:
            - "4000:27017"
        restart: "always"